### ISSUE TITLE
Unit Checker

### ISSUE THREAD

**Issue by AFifarek** [lgwagner/SpeAR#3] opened 2016-02-05 22:15 UTC
Version SpeAR 2.2.2-alpha

The unit checker is not resolving that a scalar with the associated unit is an acceptable check. Not present in version 2.2.1-alpha

The error is shown in sensor.spear with assumption a_pla_ht and a_liq_ht

[ErrorEx.zip](https://github.com/lgwagner/SpeAR/files/119936/ErrorEx.zip)

**Comment by lgwagner** [comment] 2016-02-08 20:21
This was an error caused by not providing a qualified name for imported units.

This was fixed by adding the code in SpearDeclarativeQualifiedNameProvider lines 18-20.

**Closed by lgwagner** 2016-02-08 20:21 UTC
